### ISSUE TITLE
Missing versioned dependency on watchfiles

### ISSUE THREAD

**Issue by avalentino** [conda-forge/eodag-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Apparently eodag 2.12.2 requires watchfiles>=0.13 taht is not currently available in the archive.

```
$ eodag version
eodag (Earth Observation Data Access Gateway): version 2.12.1
$ eodag discover
Traceback (most recent call last):
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/bin/eodag", line 10, in <module>
    sys.exit(eodag())
             ^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/eodag/cli.py", line 489, in discover_pt
    dag = EODataAccessGateway()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/eodag/api/core.py", line 156, in __init__
    self._plugins_manager = PluginManager(self.providers_config)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/eodag/plugins/manager.py", line 92, in __init__
    entry_point.load()
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2481, in load
    self.require(*args, **kwargs)
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2504, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/pkg_resources/__init__.py", line 798, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/nfsdata/nfsdata01/miniconda3-23.11/envs/p311/lib/python3.11/site-packages/pkg_resources/__init__.py", line 839, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'watchfiles>=0.13; extra == "standard"' distribution was not found and is required by uvicorn
```

### Installed packages

```shell
$ conda list
WARNING conda.core.prefix_data:_load_single_record(225): Ignoring malformed prefix record at: /nfsdata/nfsdata01/miniconda3-23.11/envs/p311/conda-meta/noarch_asfsmd-1.4.0-py_0.json
# packages in environment at /nfsdata/nfsdata01/miniconda3-23.11/envs/p311:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohttp                   3.9.5           py311h459d7ec_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
annotated-types           0.6.0              pyhd8ed1ab_0    conda-forge
anyio                     4.3.0              pyhd8ed1ab_0    conda-forge
argcomplete               3.3.0              pyhd8ed1ab_0    conda-forge
asf_search                7.1.1              pyhd8ed1ab_0    conda-forge
asf_search-base           7.1.1              pyhd8ed1ab_0    conda-forge
asfsmd                    1.4.0                    pypi_0    pypi
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
blinker                   1.8.2              pyhd8ed1ab_0    conda-forge
blosc                     1.21.5               hc2324a3_1    conda-forge
boto3                     1.34.103           pyhd8ed1ab_0    conda-forge
botocore                  1.34.103        pyge310_1234567_0    conda-forge
brotli-python             1.1.0           py311hb755f60_1    conda-forge
build                     0.7.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cads-api-client           1.0.1              pyhd8ed1ab_0    conda-forge
cdsapi                    0.7.0              pyhd8ed1ab_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311hb3a22ac_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
ciso8601                  2.3.1           py311h459d7ec_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cryptography              42.0.7          py311h4a61cc7_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dateparser                1.2.0              pyhd8ed1ab_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
dnspython                 2.6.1              pyhd8ed1ab_1    conda-forge
eccodes                   2.35.0               he84ddb8_0    conda-forge
ecmwf-api-client          1.6.3              pyhd8ed1ab_0    conda-forge
email-validator           2.1.1              pyhd8ed1ab_0    conda-forge
email_validator           2.1.1                hd8ed1ab_0    conda-forge
eodag                     2.12.1             pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
fastapi                   0.111.0            pyhd8ed1ab_0    conda-forge
fastapi-cli               0.0.3              pyhd8ed1ab_0    conda-forge
findlibs                  0.0.5              pyhd8ed1ab_0    conda-forge
flasgger                  0.9.7.1            pyhd8ed1ab_0    conda-forge
flask                     3.0.3              pyhd8ed1ab_0    conda-forge
freeglut                  3.2.2                hac7e632_2    conda-forge
frozenlist                1.4.1           py311h459d7ec_0    conda-forge
fsspec                    2024.3.1           pyhca7485f_0    conda-forge
geojson                   3.1.0              pyhd8ed1ab_0    conda-forge
geos                      3.12.1               h59595ed_0    conda-forge
gmp                       6.3.0                h59595ed_1    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.3          nompi_h4f84152_101    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
itsdangerous              2.2.0              pyhd8ed1ab_0    conda-forge
jasper                    4.2.4                h536e39c_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
jsonpath-ng               1.5.3              pyhd8ed1ab_0    conda-forge
jsonschema                4.22.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h55db66e_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libcurl                   8.7.1                hca28451_0    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h77fa898_7    conda-forge
libgfortran-ng            13.2.0               h69a702a_7    conda-forge
libgfortran5              13.2.0               hca663fb_7    conda-forge
libglu                    9.0.0             hac7e632_1003    conda-forge
libgomp                   13.2.0               h77fa898_7    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libmagic                  5.39                 h753d276_1    conda-forge
libnetcdf                 4.9.2           nompi_h9612171_113    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.45.3               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.12.6               h232c23b_2    conda-forge
libxslt                   1.1.39               h76b75d6_0    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lxml                      5.2.1           py311hc0a218f_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py311h459d7ec_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
multidict                 6.0.5           py311h459d7ec_0    conda-forge
multiurl                  0.3.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
numpy                     1.26.4          py311h64a7726_0    conda-forge
openssl                   3.3.0                hd590300_0    conda-forge
orjson                    3.10.3          py311h5ecf98a_0    conda-forge
owslib                    0.30.0             pyhd8ed1ab_0    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pep517                    0.13.0             pyhd8ed1ab_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
proj                      9.4.0                h1d62c97_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pycryptodome              3.20.0          py311h6601440_0    conda-forge
pydantic                  2.7.1              pyhd8ed1ab_0    conda-forge
pydantic-core             2.18.2          py311h5ecf98a_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyproj                    3.6.1           py311hb3a3e68_6    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pystac                    1.10.1             pyhd8ed1ab_0    conda-forge
python                    3.11.6          hab00c5b_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-eccodes            1.7.0           py311h1f0f07a_1    conda-forge
python-magic              0.4.27          py311h38be061_4    conda-forge
python-multipart          0.0.9              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py311h459d7ec_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
regex                     2024.5.10       py311h331c9d8_0    conda-forge
remotezip                 0.12.3             pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
requests-ftp              0.3.1                      py_1    conda-forge
requests-futures          1.0.1              pyhd8ed1ab_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
rpds-py                   0.18.1          py311h5ecf98a_0    conda-forge
s3cmd                     2.0.2                      py_0    conda-forge
s3transfer                0.10.1             pyhd8ed1ab_0    conda-forge
sentineleof               0.9.5              pyhd8ed1ab_0    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
shapely                   2.0.4           py311h2032efe_0    conda-forge
shellingham               1.5.4              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.0                hdb0a2a9_1    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.45.3               h2c6b66d_0    conda-forge
starlette                 0.37.2             pyhd8ed1ab_0    conda-forge
stream-zip                0.0.71             pyhd8ed1ab_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tenacity                  8.2.2              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
typer                     0.12.3             pyhd8ed1ab_0    conda-forge
typer-slim                0.12.3             pyhd8ed1ab_0    conda-forge
typer-slim-standard       0.12.3               hd8ed1ab_0    conda-forge
typing-extensions         4.11.0               hd8ed1ab_0    conda-forge
typing_extensions         4.11.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
tzlocal                   5.2             py311h38be061_0    conda-forge
ujson                     5.9.0           py311hb755f60_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
usgs                      0.3.5              pyhd8ed1ab_0    conda-forge
uvicorn                   0.29.0          py311h38be061_0    conda-forge
websockets                12.0            py311h459d7ec_0    conda-forge
werkzeug                  3.0.3              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
whoosh                    2.7.4           py311h38be061_8    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.8.9                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.9.4           py311h459d7ec_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
$ conda info

     active environment : p311
    active env location : /nfsdata/nfsdata01/miniconda3-23.11/envs/p311
            shell level : 1
       user config file : /home/xxxxx/xxxxx/.condarc
 populated config files : /home/xxxxx/xxxx/.condarc
                          /nfsdata/nfsdata01/miniconda3-23.11/envs/p311/.condarc
          conda version : 24.4.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=ivybridge
                          __conda=24.4.0=0
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /nfsdata/nfsdata01/miniconda3-23.11  (writable)
      conda av data dir : /nfsdata/nfsdata01/miniconda3-23.11/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /nfsdata/nfsdata01/miniconda3-23.11/pkgs
                          /home/xxxxx/xxxxx/.conda/pkgs
       envs directories : /nfsdata/nfsdata01/miniconda3-23.11/envs
                          /home/xxxxx/xxxxx/.conda/envs
               platform : linux-64
             user-agent : conda/24.4.0 requests/2.31.0 CPython/3.11.5 Linux/4.18.0-513.24.1.el8_9.x86_64 rhel/8.9 glibc/2.28 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 16777221:16777216
             netrc file : /home/xxxxx/xxxxx/.netrc
           offline mode : False
```

**Comment by sbrunato** [comment]
Thanks @avalentino for reporting this issue. `uvicorn` server-mode dependency was not properly installed
